// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231221125002_user - add responsableUPN property")]
    partial class useraddresponsableUPNproperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Empleado", b =>
                {
                    b.Property<string>("UPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableUPN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UPN");

                    b.HasIndex("ResponsableUPN");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Core.Empleado", b =>
                {
                    b.HasOne("Core.Empleado", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableUPN");

                    b.Navigation("Responsable");
                });
#pragma warning restore 612, 618
        }
    }
}
