// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231222111614_employy - fechaNacimiento to birthdate")]
    partial class employyfechaNacimientotobirthdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Employee", b =>
                {
                    b.Property<string>("UPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleUPN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UPN");

                    b.HasIndex("ResponsibleUPN");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Core.Employee", b =>
                {
                    b.HasOne("Core.Employee", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleUPN");

                    b.Navigation("Responsible");
                });
#pragma warning restore 612, 618
        }
    }
}
